import { test } from '@playwright/test';

test('', async ({ page }) => {

    //Go to https://pinterest.com
    await page.goto('https://pinterest.com');

    //pause for 3 seconds
    await page.waitForTimeout(3000);

    let blogLink = page.locator("//div[@data-test-id='header-blog-button']//a[text()='Blog']");

    blogLink.click();
    await page.waitForTimeout(3000);

});
//generated by AI, repetitive can use command to get it




